return {
    ["Blossom"] = {
        Name = "Blossom",
        Text = Color3.fromHex("#FFFFFF"),
        Button = Color3.fromHex("#FFB7C5"),
        Icon = Color3.fromHex("#FFB7C5"),
        BT = Color3.fromHex("#FFB7C5"),
    },
    ["Ocean Blue"] = {
        Name = "Ocean Blue",
        Text = Color3.fromHex("#FFFFFF"),
        Button = Color3.fromHex("#009DC4"),
        Icon = Color3.fromHex("#009DC4"),
        BT = Color3.fromHex("#009DC4"),
    },
    ["Midnight Purple"] = {
        Name = "Midnight Purple",
        Text = Color3.fromHex("#FFFFFF"),
        Button = Color3.fromHex("#5F0084"),
        Icon = Color3.fromHex("#5F0084"),
        BT = Color3.fromHex("#490066"),
    },
    ["Christmas Green"] = {
        Name = "Christmas Green",
        Text = Color3.fromHex("#FFFFFF"),
        Button = Color3.fromHex("#1E792C"),
        Icon = Color3.fromHex("#1E792C"),
        BT = Color3.fromHex("#1E792C"),
    },
}
