return {
    {
        Name = "Mint Theme",
        Accent = Color3.fromRGB(10, 186, 115),
        Background = Color3.fromRGB(24, 28, 30),
        Outline = Color3.fromRGB(45, 52, 54),
        Text = Color3.fromRGB(255, 255, 255),
        Button = Color3.fromRGB(38, 44, 46),
        Icon = Color3.fromRGB(10, 186, 115)
    },
    {
        Name = "Cyberpunk",
        Accent = Color3.fromRGB(255, 0, 127),
        Background = Color3.fromRGB(15, 10, 25),
        Outline = Color3.fromRGB(0, 255, 255),
        Text = Color3.fromRGB(255, 255, 255),
        Button = Color3.fromRGB(25, 20, 35),
        Icon = Color3.fromRGB(255, 0, 127)
    }
}
